#!/bin/sh

ADDONNAME=hm_pdetect
ADDONDIR=/usr/local/addons/${ADDONNAME}
WWWDIR=/usr/local/etc/config/addons/www/${ADDONNAME}
RCDDIR=/usr/local/etc/config/rc.d

# function that starts hm_pdetect as a daemon
start() {
  # default settings (will be overwritten by config file)
  export HM_PROCESSLOG_FILE="/var/log/hm_pdetect.log"
  export HM_INTERVAL_TIME=15
  export CONFIG_FILE="${ADDONDIR}/etc/hm_pdetect.conf"

  # set path settings to let it search in the bin directory as well.
  export PATH="${ADDONDIR}/bin:${PATH}"

  # run hm_pdetect in daemon mode
  ${ADDONDIR}/bin/hm_pdetect.sh start >/dev/null 2>&1
}

# function that stops/kills hm_pdetect
stop() {
  # default settings (will be overwritten by config file)
  export CONFIG_FILE="${ADDONDIR}/etc/hm_pdetect.conf"

  # set path settings to let it search in the bin directory as well.
  export PATH="${ADDONDIR}/bin:${PATH}"

  # stop/kill hm_pdetect
  ${ADDONDIR}/bin/hm_pdetect.sh stop >/dev/null 2>&1
}

case "$1" in

  ""|start)
    start
    ;;

  stop)
    stop
    ;;

  restart|reload)
    stop
    sleep 2
    start
    ;;

  info)
    echo "Info: <b>FRITZ!-based Presence Detection Addon</b><br>"
    echo "Info: (c) 2015-2016 Jens Maus<br>"
    echo "Info: <a href='http://github.com/jens-maus/hm_pdetect'>http://github.com/jens-maus/hm_pdetect</a>"
    echo "Version: $(cat ${WWWDIR}/VERSION)"
    echo "Name: hm_pdetect"
    echo "Operations: uninstall restart"
    echo "Config-Url: /addons/${ADDONNAME}/"
    echo "Update: /addons/${ADDONNAME}/update-check.cgi"
    ;;

  uninstall)
    # make sure to stop hm_pdetect
    stop

    # remove the addon button
    ${ADDONDIR}/bin/update_addon hm_pdetect

    # remove the whole addon related stuff
    rm -rf ${ADDONDIR}
    rm -rf ${WWWDIR}
    rm -f ${RCDDIR}/${ADDONNAME}
    ;;

  *)
    echo "Usage: hm_pdetect {start|stop|restart|info|uninstall}" >&2
    exit 1
    ;;

esac

exit $?
